name: Tests

on: [ push, pull_request ]


jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - run: dotnet tool install -g coveralls.net
      - name: COveralls
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
        run: csmacnz.Coveralls --opencover -i Bynder/Test/coverage.opencover.xml --useRelativePaths
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: /home/runner/work/bynder-c-sharp-sdk/bynder-c-sharp-sdk/coverage/lcov.info

